// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brokerRemotingService.proto

package com.song.fastmq.net.proto;

public final class BrokerRemotingApi {
  private BrokerRemotingApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProducerRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.song.fastmq.broker.net.ProducerRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string topic = 1;</code>
     */
    java.lang.String getTopic();
    /**
     * <code>string topic = 1;</code>
     */
    com.google.protobuf.ByteString
        getTopicBytes();

    /**
     * <code>uint64 producer_id = 2;</code>
     */
    long getProducerId();

    /**
     * <pre>
     *&#47; If a producer name is specified, the name will be used,
     * / otherwise the broker will generate a unique name
     * </pre>
     *
     * <code>string producer_name = 3;</code>
     */
    java.lang.String getProducerName();
    /**
     * <pre>
     *&#47; If a producer name is specified, the name will be used,
     * / otherwise the broker will generate a unique name
     * </pre>
     *
     * <code>string producer_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getProducerNameBytes();
  }
  /**
   * <pre>
   *&#47; Create a new Producer on a topic, assigning the given producer_id,
   * / all messages sent with this producer_id will be persisted on the topic
   * </pre>
   *
   * Protobuf type {@code com.song.fastmq.broker.net.ProducerRequest}
   */
  public  static final class ProducerRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.song.fastmq.broker.net.ProducerRequest)
      ProducerRequestOrBuilder {
    // Use ProducerRequest.newBuilder() to construct.
    private ProducerRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProducerRequest() {
      topic_ = "";
      producerId_ = 0L;
      producerName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ProducerRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              topic_ = s;
              break;
            }
            case 16: {

              producerId_ = input.readUInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              producerName_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.song.fastmq.net.proto.BrokerRemotingApi.internal_static_com_song_fastmq_broker_net_ProducerRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.song.fastmq.net.proto.BrokerRemotingApi.internal_static_com_song_fastmq_broker_net_ProducerRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest.class, com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest.Builder.class);
    }

    public static final int TOPIC_FIELD_NUMBER = 1;
    private volatile java.lang.Object topic_;
    /**
     * <code>string topic = 1;</code>
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      }
    }
    /**
     * <code>string topic = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCER_ID_FIELD_NUMBER = 2;
    private long producerId_;
    /**
     * <code>uint64 producer_id = 2;</code>
     */
    public long getProducerId() {
      return producerId_;
    }

    public static final int PRODUCER_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object producerName_;
    /**
     * <pre>
     *&#47; If a producer name is specified, the name will be used,
     * / otherwise the broker will generate a unique name
     * </pre>
     *
     * <code>string producer_name = 3;</code>
     */
    public java.lang.String getProducerName() {
      java.lang.Object ref = producerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        producerName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *&#47; If a producer name is specified, the name will be used,
     * / otherwise the broker will generate a unique name
     * </pre>
     *
     * <code>string producer_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProducerNameBytes() {
      java.lang.Object ref = producerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        producerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTopicBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, topic_);
      }
      if (producerId_ != 0L) {
        output.writeUInt64(2, producerId_);
      }
      if (!getProducerNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, producerName_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTopicBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, topic_);
      }
      if (producerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, producerId_);
      }
      if (!getProducerNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, producerName_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest)) {
        return super.equals(obj);
      }
      com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest other = (com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest) obj;

      boolean result = true;
      result = result && getTopic()
          .equals(other.getTopic());
      result = result && (getProducerId()
          == other.getProducerId());
      result = result && getProducerName()
          .equals(other.getProducerName());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getTopic().hashCode();
      hash = (37 * hash) + PRODUCER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProducerId());
      hash = (37 * hash) + PRODUCER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getProducerName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *&#47; Create a new Producer on a topic, assigning the given producer_id,
     * / all messages sent with this producer_id will be persisted on the topic
     * </pre>
     *
     * Protobuf type {@code com.song.fastmq.broker.net.ProducerRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.song.fastmq.broker.net.ProducerRequest)
        com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.song.fastmq.net.proto.BrokerRemotingApi.internal_static_com_song_fastmq_broker_net_ProducerRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.song.fastmq.net.proto.BrokerRemotingApi.internal_static_com_song_fastmq_broker_net_ProducerRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest.class, com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest.Builder.class);
      }

      // Construct using com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        topic_ = "";

        producerId_ = 0L;

        producerName_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.song.fastmq.net.proto.BrokerRemotingApi.internal_static_com_song_fastmq_broker_net_ProducerRequest_descriptor;
      }

      public com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest getDefaultInstanceForType() {
        return com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest.getDefaultInstance();
      }

      public com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest build() {
        com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest buildPartial() {
        com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest result = new com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest(this);
        result.topic_ = topic_;
        result.producerId_ = producerId_;
        result.producerName_ = producerName_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest) {
          return mergeFrom((com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest other) {
        if (other == com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest.getDefaultInstance()) return this;
        if (!other.getTopic().isEmpty()) {
          topic_ = other.topic_;
          onChanged();
        }
        if (other.getProducerId() != 0L) {
          setProducerId(other.getProducerId());
        }
        if (!other.getProducerName().isEmpty()) {
          producerName_ = other.producerName_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object topic_ = "";
      /**
       * <code>string topic = 1;</code>
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          topic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string topic = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string topic = 1;</code>
       */
      public Builder setTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 1;</code>
       */
      public Builder clearTopic() {
        
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 1;</code>
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        topic_ = value;
        onChanged();
        return this;
      }

      private long producerId_ ;
      /**
       * <code>uint64 producer_id = 2;</code>
       */
      public long getProducerId() {
        return producerId_;
      }
      /**
       * <code>uint64 producer_id = 2;</code>
       */
      public Builder setProducerId(long value) {
        
        producerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 producer_id = 2;</code>
       */
      public Builder clearProducerId() {
        
        producerId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object producerName_ = "";
      /**
       * <pre>
       *&#47; If a producer name is specified, the name will be used,
       * / otherwise the broker will generate a unique name
       * </pre>
       *
       * <code>string producer_name = 3;</code>
       */
      public java.lang.String getProducerName() {
        java.lang.Object ref = producerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          producerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *&#47; If a producer name is specified, the name will be used,
       * / otherwise the broker will generate a unique name
       * </pre>
       *
       * <code>string producer_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getProducerNameBytes() {
        java.lang.Object ref = producerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          producerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *&#47; If a producer name is specified, the name will be used,
       * / otherwise the broker will generate a unique name
       * </pre>
       *
       * <code>string producer_name = 3;</code>
       */
      public Builder setProducerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        producerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; If a producer name is specified, the name will be used,
       * / otherwise the broker will generate a unique name
       * </pre>
       *
       * <code>string producer_name = 3;</code>
       */
      public Builder clearProducerName() {
        
        producerName_ = getDefaultInstance().getProducerName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; If a producer name is specified, the name will be used,
       * / otherwise the broker will generate a unique name
       * </pre>
       *
       * <code>string producer_name = 3;</code>
       */
      public Builder setProducerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        producerName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.song.fastmq.broker.net.ProducerRequest)
    }

    // @@protoc_insertion_point(class_scope:com.song.fastmq.broker.net.ProducerRequest)
    private static final com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest();
    }

    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProducerRequest>
        PARSER = new com.google.protobuf.AbstractParser<ProducerRequest>() {
      public ProducerRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProducerRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProducerRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProducerRequest> getParserForType() {
      return PARSER;
    }

    public com.song.fastmq.net.proto.BrokerRemotingApi.ProducerRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProducerSuccessReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.song.fastmq.broker.net.ProducerSuccessReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string producer_name = 1;</code>
     */
    java.lang.String getProducerName();
    /**
     * <code>string producer_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getProducerNameBytes();

    /**
     * <code>uint64 producer_id = 2;</code>
     */
    long getProducerId();
  }
  /**
   * <pre>
   *&#47; Response from CommandProducer
   * </pre>
   *
   * Protobuf type {@code com.song.fastmq.broker.net.ProducerSuccessReply}
   */
  public  static final class ProducerSuccessReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.song.fastmq.broker.net.ProducerSuccessReply)
      ProducerSuccessReplyOrBuilder {
    // Use ProducerSuccessReply.newBuilder() to construct.
    private ProducerSuccessReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProducerSuccessReply() {
      producerName_ = "";
      producerId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ProducerSuccessReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              producerName_ = s;
              break;
            }
            case 16: {

              producerId_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.song.fastmq.net.proto.BrokerRemotingApi.internal_static_com_song_fastmq_broker_net_ProducerSuccessReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.song.fastmq.net.proto.BrokerRemotingApi.internal_static_com_song_fastmq_broker_net_ProducerSuccessReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply.class, com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply.Builder.class);
    }

    public static final int PRODUCER_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object producerName_;
    /**
     * <code>string producer_name = 1;</code>
     */
    public java.lang.String getProducerName() {
      java.lang.Object ref = producerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        producerName_ = s;
        return s;
      }
    }
    /**
     * <code>string producer_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProducerNameBytes() {
      java.lang.Object ref = producerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        producerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCER_ID_FIELD_NUMBER = 2;
    private long producerId_;
    /**
     * <code>uint64 producer_id = 2;</code>
     */
    public long getProducerId() {
      return producerId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getProducerNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, producerName_);
      }
      if (producerId_ != 0L) {
        output.writeUInt64(2, producerId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getProducerNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, producerName_);
      }
      if (producerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, producerId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply)) {
        return super.equals(obj);
      }
      com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply other = (com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply) obj;

      boolean result = true;
      result = result && getProducerName()
          .equals(other.getProducerName());
      result = result && (getProducerId()
          == other.getProducerId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRODUCER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getProducerName().hashCode();
      hash = (37 * hash) + PRODUCER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProducerId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *&#47; Response from CommandProducer
     * </pre>
     *
     * Protobuf type {@code com.song.fastmq.broker.net.ProducerSuccessReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.song.fastmq.broker.net.ProducerSuccessReply)
        com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.song.fastmq.net.proto.BrokerRemotingApi.internal_static_com_song_fastmq_broker_net_ProducerSuccessReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.song.fastmq.net.proto.BrokerRemotingApi.internal_static_com_song_fastmq_broker_net_ProducerSuccessReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply.class, com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply.Builder.class);
      }

      // Construct using com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        producerName_ = "";

        producerId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.song.fastmq.net.proto.BrokerRemotingApi.internal_static_com_song_fastmq_broker_net_ProducerSuccessReply_descriptor;
      }

      public com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply getDefaultInstanceForType() {
        return com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply.getDefaultInstance();
      }

      public com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply build() {
        com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply buildPartial() {
        com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply result = new com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply(this);
        result.producerName_ = producerName_;
        result.producerId_ = producerId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply) {
          return mergeFrom((com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply other) {
        if (other == com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply.getDefaultInstance()) return this;
        if (!other.getProducerName().isEmpty()) {
          producerName_ = other.producerName_;
          onChanged();
        }
        if (other.getProducerId() != 0L) {
          setProducerId(other.getProducerId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object producerName_ = "";
      /**
       * <code>string producer_name = 1;</code>
       */
      public java.lang.String getProducerName() {
        java.lang.Object ref = producerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          producerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string producer_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getProducerNameBytes() {
        java.lang.Object ref = producerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          producerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string producer_name = 1;</code>
       */
      public Builder setProducerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        producerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string producer_name = 1;</code>
       */
      public Builder clearProducerName() {
        
        producerName_ = getDefaultInstance().getProducerName();
        onChanged();
        return this;
      }
      /**
       * <code>string producer_name = 1;</code>
       */
      public Builder setProducerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        producerName_ = value;
        onChanged();
        return this;
      }

      private long producerId_ ;
      /**
       * <code>uint64 producer_id = 2;</code>
       */
      public long getProducerId() {
        return producerId_;
      }
      /**
       * <code>uint64 producer_id = 2;</code>
       */
      public Builder setProducerId(long value) {
        
        producerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 producer_id = 2;</code>
       */
      public Builder clearProducerId() {
        
        producerId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.song.fastmq.broker.net.ProducerSuccessReply)
    }

    // @@protoc_insertion_point(class_scope:com.song.fastmq.broker.net.ProducerSuccessReply)
    private static final com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply();
    }

    public static com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProducerSuccessReply>
        PARSER = new com.google.protobuf.AbstractParser<ProducerSuccessReply>() {
      public ProducerSuccessReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProducerSuccessReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProducerSuccessReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProducerSuccessReply> getParserForType() {
      return PARSER;
    }

    public com.song.fastmq.net.proto.BrokerRemotingApi.ProducerSuccessReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_song_fastmq_broker_net_ProducerRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_song_fastmq_broker_net_ProducerRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_song_fastmq_broker_net_ProducerSuccessReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_song_fastmq_broker_net_ProducerSuccessReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033brokerRemotingService.proto\022\032com.song." +
      "fastmq.broker.net\"L\n\017ProducerRequest\022\r\n\005" +
      "topic\030\001 \001(\t\022\023\n\013producer_id\030\002 \001(\004\022\025\n\rprod" +
      "ucer_name\030\003 \001(\t\"B\n\024ProducerSuccessReply\022" +
      "\025\n\rproducer_name\030\001 \001(\t\022\023\n\013producer_id\030\002 " +
      "\001(\0042\221\001\n\025BrokerRemotingService\022x\n\025handleP" +
      "roducerRequest\022+.com.song.fastmq.broker." +
      "net.ProducerRequest\0320.com.song.fastmq.br" +
      "oker.net.ProducerSuccessReply\"\000B.\n\031com.s" +
      "ong.fastmq.net.protoB\021BrokerRemotingApib",
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_song_fastmq_broker_net_ProducerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_song_fastmq_broker_net_ProducerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_song_fastmq_broker_net_ProducerRequest_descriptor,
        new java.lang.String[] { "Topic", "ProducerId", "ProducerName", });
    internal_static_com_song_fastmq_broker_net_ProducerSuccessReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_song_fastmq_broker_net_ProducerSuccessReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_song_fastmq_broker_net_ProducerSuccessReply_descriptor,
        new java.lang.String[] { "ProducerName", "ProducerId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
